name: javiertest
favicon: null
layout_spectrum: 0.5652439226396382
typography_spectrum: 0.7421564250253141
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3133087947499007
  lightness: 0.29710043547675014
  saturation: 0.7877679832745343
  rhythmicContrast: 0.9218722097575665
purpose: []
